@include('zADMIN.PAGE._lego.filter._lego.filter_for_table.brick.btn_lvl_1')
@component('zADMIN._wrap.manager.btn.localStorage_toggle',['css' => 'x-exclude'])
    @slot('localstorageName','filter_btn_table_level_1')
    @slot('dataCheck','y-childrenLevel_1_off')
    @slot('nodeName','Table_index')
    @slot('toggleCss','y-childrenLevel_1_off')
    @slot('name','lvl 2')
@endcomponent
@component('zADMIN._wrap.manager.btn.localStorage_toggle',['css' => 'x-exclude'])
    @slot('localstorageName','filter_btn_table_level_2')
    @slot('dataCheck','y-childrenLevel_2_off')
    @slot('nodeName','Table_index')
    @slot('toggleCss','y-childrenLevel_2_off')
    @slot('name','lvl 3')
@endcomponent
@component('zADMIN._wrap.manager.btn.localStorage_toggle',['css' => 'x-exclude'])
    @slot('localstorageName','filter_btn_table_level_3')
    @slot('dataCheck','y-childrenLevel_3_off')
    @slot('nodeName','Table_index')
    @slot('toggleCss','y-childrenLevel_3_off')
    @slot('name','lvl 4')
@endcomponent
@component('zADMIN._wrap.manager.btn.localStorage_toggle',['css' => 'x-exclude'])
    @slot('localstorageName','filter_btn_table_level_4')
    @slot('dataCheck','y-childrenLevel_4_off')
    @slot('nodeName','Table_index')
    @slot('toggleCss','y-childrenLevel_4_off')
    @slot('name','lvl 5')
@endcomponent
@component('zADMIN._wrap.manager.btn.localStorage_toggle',['css' => 'x-exclude'])
    @slot('localstorageName','filter_btn_table_childrenLevel')
    @slot('dataCheck','y-childrenLevelOff')
    @slot('nodeName','Table_index')
    @slot('toggleCss','y-childrenLevelOff')
    @slot('name','children')
@endcomponent